import React, { useState } from "react";
import {
  ArrowLeft,
  Check,
  AlertTriangle,
  Flame,
  Droplet,
  Sun,
  ShieldCheck,
  HeartPulse,
  Wrench,
  Sparkles,
  Award,
  BookOpen,
  Sprout,
  Activity,
  CheckCircle,
  Volume2,
  VolumeX,
  Download,
  Printer
} from "lucide-react";
import { DiagnosticReport } from "../types";
import { parseInlineStyles } from "./FormattedText";

interface DiagnosticReportViewProps {
  report: DiagnosticReport;
  imageData: string;
  onBack?: () => void;
  inlineMode?: boolean;
}

export default function DiagnosticReportView({ report, imageData, onBack, inlineMode = false }: DiagnosticReportViewProps) {
  const [checkedRecoverySteps, setCheckedRecoverySteps] = useState<Record<number, boolean>>({});
  const [isSpeaking, setIsSpeaking] = useState(false);

  const isHealthy = report.status === "healthy";

  // Dynamic colors based on severity
  const getSeverityStyles = (severity: string) => {
    switch (severity.toLowerCase()) {
      case "critical":
        return { bg: "bg-red-50", text: "text-red-700", border: "border-red-200", bar: "bg-red-600" };
      case "high":
        return { bg: "bg-orange-50", text: "text-orange-700", border: "border-orange-200", bar: "bg-orange-600" };
      case "medium":
        return { bg: "bg-yellow-50", text: "text-yellow-700", border: "border-yellow-250", bar: "bg-yellow-500" };
      default:
        return { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200", bar: "bg-emerald-600" };
    }
  };

  const severityStyle = getSeverityStyles(report.severity);

  const toggleRecoveryStep = (index: number) => {
    setCheckedRecoverySteps((prev) => ({
      ...prev,
      [index]: !prev[index],
    }));
  };

  // Voice output logic (Web Speech Synthesis API)
  const handleHearSpeech = () => {
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    window.speechSynthesis.cancel(); // Stop prior speeches if any

    const linesToSpeak = [
      `Diagnostic report for ${report.plantType}.`,
      `Identified issue is ${report.issueName}.`,
      `Severity is considered ${report.severity}.`,
      `The top organic remedy is: ${report.organicTreatments[0] || "None required."}`,
      `Please consult the recovery journey checklist to nurse this specimen back to health.`
    ];

    const utterance = new SpeechSynthesisUtterance(linesToSpeak.join(" "));
    utterance.rate = 1.0;
    utterance.pitch = 1.01;

    utterance.onend = () => {
      setIsSpeaking(false);
    };

    utterance.onerror = () => {
      setIsSpeaking(false);
    };

    setIsSpeaking(true);
    window.speechSynthesis.speak(utterance);
  };

  // Downloadable report creator (.md format)
  const handleDownloadReport = () => {
    const reportTitle = report.issueName.replace(/\s+/g, "_").toLowerCase();
    const markdownContent = `# AI BOTANICAL CLINIC - DIAGNOSTIC REPORT
Date of Scan: ${new Date().toLocaleDateString()}
Target Plant: ${report.plantType}
Diagnosed Condition: ${report.issueName}
Health Status: ${report.status.toUpperCase()}
System Confidence: ${report.confidence}%
Severity Urgent Index: ${report.severity}

## 1. VISUAL ANOMALIES & SYMPTOMS
${report.symptoms.map(s => `- ${s}`).join("\n")}

## 2. ROOT CAUSES & TRIGGERS
${report.causes.map(c => `- ${c}`).join("\n")}

## 3. CORE REMEDIES & TREATMENTS
### Organic Herbal Solutions:
${report.organicTreatments.map(t => `- ${t}`).join("\n")}

### Chemical / Fertilizer Options:
${report.chemicalTreatments.map(ch => `- ${ch}`).join("\n")}

### Quick Home Recipes:
${report.homeRemedies.map(r => `- ${r}`).join("\n")}

## 4. ESSENTIAL CULTIVATION PATHWAYS
- Soil chemistry advice: ${report.soilNutrients}
- Direct Irrigation guidance: ${report.wateringAdvice}
- Sunlight exposure: ${report.sunlightAdvice}

## 5. FUTURE PREVENTION STRATEGIES
${report.prevention.map(p => `- ${p}`).join("\n")}

## 6. CLINICAL STEP-BY-STEP RECOVERY JOURNEY
${report.recoverySteps.map((rc, idx) => `${idx + 1}. [ ] ${rc}`).join("\n")}

---
Generated by AI Plant Doctor Clinical Assistant.
`;

    const blob = new Blob([markdownContent], { type: "text/markdown;charset=utf-8" });
    const blobUrl = URL.createObjectURL(blob);
    
    const downloadAnchor = document.createElement("a");
    downloadAnchor.href = blobUrl;
    downloadAnchor.download = `plant_doc_report_${reportTitle}.md`;
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    
    // Clean up
    document.body.removeChild(downloadAnchor);
    URL.revokeObjectURL(blobUrl);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className={`w-full max-w-5xl mx-auto bg-white text-neutral-800 animate-fade-in print:p-0 ${inlineMode ? "px-0 py-2" : "px-6 py-8 md:py-12"}`}>
      
      {/* Upper Navigation Row (Clean ChatGPT White bar) */}
      <div className={`flex flex-col sm:flex-row sm:items-center gap-3 mb-6 md:mb-10 print:hidden border-b border-neutral-100 pb-5 ${inlineMode ? "justify-end" : "justify-between"}`}>
        {!inlineMode && onBack && (
          <button
            onClick={onBack}
            className="group px-4 py-2.5 bg-neutral-900 border border-neutral-950 hover:bg-neutral-850 text-white rounded-xl text-xs font-semibold flex items-center justify-center gap-2 cursor-pointer transition-all duration-150"
          >
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform" />
            <span>Upload Image</span>
          </button>
        )}

        <div className="flex flex-wrap items-center gap-2">
          {/* Voice Speech Trigger */}
          <button
            onClick={handleHearSpeech}
            className={`px-3.5 py-2.5 border rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 cursor-pointer transition-colors ${
              isSpeaking
                ? "bg-red-50 border-red-200 text-red-700 hover:bg-red-100"
                : "bg-white border-neutral-200 text-neutral-700 hover:bg-neutral-50"
            }`}
            title="Listen to diagnosis text to speech"
          >
            {isSpeaking ? (
              <>
                <VolumeX className="w-4 h-4 text-red-650" />
                <span>Mute Reader</span>
              </>
            ) : (
              <>
                <Volume2 className="w-4 h-4 text-emerald-600 animate-pulse" />
                <span>Hear Diagnosis Speech</span>
              </>
            )}
          </button>

          {/* Report download button */}
          <button
            onClick={handleDownloadReport}
            className="px-3.5 py-2.5 bg-white border border-neutral-200 hover:bg-neutral-50 text-neutral-700 rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 cursor-pointer transition-colors"
          >
            <Download className="w-4 h-4 text-blue-600" />
            <span>Download Text Report</span>
          </button>

          {/* Standard print action */}
          <button
            onClick={handlePrint}
            className="px-3.5 py-2.5 bg-white border border-neutral-200 hover:bg-neutral-50 text-neutral-700 rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 cursor-pointer transition-colors"
          >
            <Printer className="w-4 h-4 text-neutral-500" />
            <span>Print Report</span>
          </button>
        </div>
      </div>

      {/* Main Structural Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 leading-relaxed">
        
        {/* Left column: Image Frame & Diagnostics Metres (lg: 4 cols) */}
        <section className="lg:col-span-4 flex flex-col gap-8">
          {/* Leaf image container */}
          <div className="p-0">
            <h3 className="text-[10px] font-bold text-neutral-400 uppercase tracking-widest mb-3 font-display">
              Analyzed Leaf Sample
            </h3>
            <div className={`relative aspect-square rounded-xl overflow-hidden bg-neutral-50 flex items-center justify-center border ${isHealthy ? "border-emerald-200" : "border-amber-200"}`}>
              <img
                src={imageData}
                alt="Analyzed leaf specimen"
                className="w-full h-full object-contain"
                referrerPolicy="no-referrer"
              />
              <div className="absolute top-3 right-3 flex flex-col gap-1.5 z-10">
                {/* Healthy Pill */}
                {isHealthy ? (
                  <span className="px-3 py-1 text-[10px] font-bold tracking-wider font-display rounded-full bg-emerald-500 text-white flex items-center gap-1 shadow-sm">
                    <CheckCircle className="w-3.5 h-3.5" />
                    HEALTHY
                  </span>
                ) : (
                  <span className="px-3 py-1 text-[10px] font-bold tracking-wider font-display rounded-full bg-red-650 text-white flex items-center gap-1 shadow-sm">
                    <AlertTriangle className="w-3.5 h-3.5" />
                    UNHEALTHY
                  </span>
                )}
              </div>
            </div>
            
            {/* Specimen Info footer */}
            <div className="mt-4 pt-4 border-t border-neutral-100 grid grid-cols-2 gap-2 text-center">
              <div className="py-2">
                <p className="text-[9px] font-bold text-neutral-405 font-mono">PLANT SPECIES</p>
                <p className="text-xs font-semibold text-neutral-800 mt-0.5 truncate">{report.plantType}</p>
              </div>
              <div className="py-2 border-l border-neutral-100">
                <p className="text-[9px] font-bold text-neutral-405 font-mono">ACCURACY</p>
                <p className="text-xs font-semibold text-neutral-905 mt-0.5 font-mono">{report.confidence}% Match</p>
              </div>
            </div>
          </div>

          {/* Quick Metrics Card */}
          {!isHealthy && (
            <div className="p-0 border-t border-neutral-100 pt-6">
              <h4 className="text-[10px] font-bold text-neutral-405 uppercase tracking-widest mb-4 font-display">
                Urgency Intensity Scores
              </h4>
              
              <div className="space-y-4">
                {/* Severity Metre */}
                <div>
                  <div className="flex justify-between items-center text-xs mb-1.5">
                    <span className="text-neutral-500 font-medium">Severity Intensity:</span>
                    <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase font-mono border ${severityStyle.bg} ${severityStyle.text} ${severityStyle.border}`}>
                      {report.severity}
                    </span>
                  </div>
                  {/* Visual Progress Bar */}
                  <div className="w-full h-1.5 bg-neutral-100 rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full transition-all duration-1000 ${severityStyle.bar}`}
                      style={{
                        width:
                          report.severity.toLowerCase() === "critical"
                            ? "100%"
                            : report.severity.toLowerCase() === "high"
                            ? "75%"
                            : report.severity.toLowerCase() === "medium"
                            ? "45%"
                            : "10%",
                      }}
                    />
                  </div>
                </div>
  
                {/* Confidence Meter */}
                <div>
                  <div className="flex justify-between items-center text-xs mb-1.5">
                    <span className="text-neutral-500 font-medium">Accuracy Confidence:</span>
                    <span className="text-neutral-900 font-bold font-mono text-[11px]">{report.confidence}%</span>
                  </div>
                  <div className="w-full h-1.5 bg-neutral-100 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-black rounded-full transition-all duration-1000"
                      style={{ width: `${report.confidence}%` }}
                    />
                  </div>
                </div>
              </div>
  
              <div className="mt-5 text-[11px] text-neutral-450 leading-relaxed font-mono flex gap-2">
                <span className="text-emerald-600">💡</span>
                <span>Our clinical model evaluates foliage cells against international botanical records.</span>
              </div>
            </div>
          )}
        </section>

        {/* Right column: Beautiful tabbed reports and checklists (lg: 8 cols) */}
        <div className="lg:col-span-8 flex flex-col gap-6">
          {/* Main Title Banner board */}
          <div className="pb-5 border-b border-neutral-100">
            <div className="flex items-center gap-2 mb-2">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-ping"></span>
              <span className="text-[10px] uppercase tracking-widest font-bold text-emerald-700 font-mono">
                Official AI Diagnosis Match
              </span>
            </div>
            <h1 className="font-display font-medium text-3xl text-neutral-900 leading-tight">
              {report.issueName}
            </h1>
            <p className="text-xs text-neutral-450 font-mono mt-1.5">
              Subject crop: <span className="text-neutral-700 font-semibold">{report.plantType}</span>
            </p>
          </div>

          {!isHealthy ? (
            <>
              {/* Quick Jump / Navigation shortcuts */}
              <div className="flex gap-2 overflow-x-auto scrollbar pb-2 print:hidden border-b border-neutral-100">
                {[
                  { id: "results-sec", label: "Diagnosis & Symptoms", icon: BookOpen },
                  { id: "treatments-sec", label: "Treatment & Cures", icon: Wrench },
                  { id: "prevention-sec", label: "Prevention & Protection", icon: ShieldCheck },
                  { id: "care-sec", label: "Soil & Water Care", icon: Sprout },
                  { id: "actions-sec", label: "Recovery Action Plan", icon: HeartPulse },
                ].map((tab) => {
                  const TabIcon = tab.icon;
                  return (
                    <button
                      key={tab.id}
                      onClick={() => {
                        const el = document.getElementById(tab.id);
                        if (el) {
                          el.scrollIntoView({ behavior: "smooth", block: "center" });
                        }
                      }}
                      className="flex items-center gap-1.5 py-1.5 px-2.5 rounded-lg font-display text-xs transition-all text-neutral-500 hover:text-neutral-900 font-medium whitespace-forward cursor-pointer hover:bg-neutral-50"
                    >
                      <TabIcon className="w-3.5 h-3.5 text-emerald-600" />
                      <span>{tab.label}</span>
                    </button>
                  );
                })}
              </div>
    
              {/* UNIFIED COMPREHENSIVE BOTANICAL BRIEF SHEET (Fully Expanded - No hidden content) */}
              <div className="space-y-10">
                
                {/* 1. DIAGNOSIS RESULTS CARD */}
                <section id="results-sec" className="scroll-mt-6 animate-fade-in">
                  <div className="space-y-6">
                    <div>
                      <h2 className="text-xs md:text-sm font-bold text-neutral-500 uppercase tracking-widest mb-3 border-b border-neutral-100 pb-2 flex items-center gap-2 font-display">
                        <Activity className="w-4 h-4 text-emerald-600" />
                        Detected Visual Symptoms
                      </h2>
                      <ul className="space-y-3">
                        {report.symptoms.map((symptom, idx) => (
                          <li key={idx} className="text-sm md:text-[15px] text-neutral-800 flex items-start gap-2.5">
                            <span className="inline-flex w-1.5 h-1.5 bg-emerald-500 rounded-full mt-2 shrink-0" />
                            <span>{parseInlineStyles(symptom)}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
    
                    <div>
                      <h2 className="text-xs md:text-sm font-bold text-neutral-500 uppercase tracking-widest mb-3 border-b border-neutral-100 pb-2 flex items-center gap-2 font-display">
                        <AlertTriangle className="w-4 h-4 text-amber-500" />
                        Probable Causes of This Condition
                      </h2>
                      <ul className="space-y-3">
                        {report.causes.map((cause, idx) => (
                          <li key={idx} className="text-sm md:text-[15px] text-neutral-800 flex items-start gap-2.5">
                            <span className="inline-flex w-1.5 h-1.5 bg-amber-500 rounded-full mt-2 shrink-0" />
                            <span>{parseInlineStyles(cause)}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </section>
    
                {/* 2. TREATMENT RECOMMENDATIONS & CURES CARD */}
                <section id="treatments-sec" className="scroll-mt-6 animate-fade-in border-t border-neutral-100 pt-6">
                   <div className="space-y-6">
                     {/* Organic solutions */}
                     <div>
                       <div className="flex items-center gap-2 mb-3 border-b border-neutral-100 pb-2">
                         <Sprout className="w-4 h-4 text-emerald-650" />
                        <h2 className="text-xs md:text-sm font-bold text-neutral-500 uppercase tracking-widest font-display">
                           Organic Botanical Treatments (How to Cure)
                         </h2>
                       </div>
                      <ul className="space-y-3">
                         {report.organicTreatments.map((treatment, idx) => (
                          <li key={idx} className="text-sm md:text-[15px] text-neutral-800 flex items-start gap-3 py-1">
                             <span className="text-base leading-none select-none">🍃</span>
                             <span>{parseInlineStyles(treatment)}</span>
                           </li>
                         ))}
                       </ul>
                     </div>
     
                     {/* Chemical treatments */}
                     {report.chemicalTreatments.length > 0 && (
                       <div>
                         <div className="flex items-center gap-2 mb-3 border-b border-neutral-100 pb-2">
                           <Flame className="w-4 h-4 text-cyan-600" />
                          <h2 className="text-xs md:text-sm font-bold text-neutral-500 uppercase tracking-widest font-display">
                             Chemical & Fertilizer Treatments
                           </h2>
                         </div>
                        <ul className="space-y-3">
                           {report.chemicalTreatments.map((chem, idx) => (
                            <li key={idx} className="text-sm md:text-[15px] text-neutral-800 flex items-start gap-3 py-1">
                               <span className="text-base leading-none select-none">🧪</span>
                               <span>{parseInlineStyles(chem)}</span>
                             </li>
                           ))}
                         </ul>
                       </div>
                     )}
     
                     {/* Home Remedies */}
                     <div>
                       <div className="flex items-center gap-2 mb-3 border-b border-neutral-100 pb-2">
                         <Sparkles className="w-3.5 h-3.5 text-yellow-500 animate-pulse" />
                        <h2 className="text-xs md:text-sm font-bold text-neutral-500 uppercase tracking-widest font-display">
                           Proven Household Remedies (Quick DIY Cures)
                         </h2>
                       </div>
                      <ul className="space-y-3">
                         {report.homeRemedies.map((remedy, idx) => (
                          <li key={idx} className="text-sm md:text-[15px] text-neutral-800 flex items-start gap-3 py-1">
                             <span className="text-base leading-none select-none">🏠</span>
                             <span>{parseInlineStyles(remedy)}</span>
                           </li>
                         ))}
                       </ul>
                     </div>
                   </div>
                </section>
    
                {/* 3. PREVENTION TIPS CARD */}
                <section id="prevention-sec" className="scroll-mt-6 animate-fade-in border-t border-neutral-100 pt-6">
                   <div className="space-y-4 animate-fade-in">
                     <div className="flex items-center gap-2 mb-3 border-b border-neutral-100 pb-2">
                       <ShieldCheck className="w-4 h-4 text-emerald-600" />
                      <h2 className="text-xs md:text-sm font-bold text-neutral-500 uppercase tracking-widest font-display">
                         Future Cultivation Protection (How to Prevent)
                       </h2>
                     </div>
                    <ul className="space-y-3.5">
                       {report.prevention.map((prev, idx) => (
                         <li key={idx} className="py-1 flex items-start gap-3">
                           <div className="text-emerald-600 shrink-0 mt-0.5">
                             <Check className="w-3.5 h-3.5 stroke-[2.5]" />
                           </div>
                          <span className="text-sm md:text-[15px] text-neutral-800 leading-normal">{parseInlineStyles(prev)}</span>
                         </li>
                       ))}
                     </ul>
                   </div>
                 </section>
    
                {/* 4. PLANT CARE ADVICE CARD */}
                <section id="care-sec" className="scroll-mt-6 animate-fade-in border-t border-neutral-100 pt-6">
                   <div className="space-y-6 animate-fade-in">
                     {/* Soil & Nutrients */}
                    <div className="leading-relaxed text-sm md:text-[15px] text-neutral-805">
                      <div className="flex items-center gap-2 mb-3 text-neutral-900 font-semibold text-xs md:text-sm font-display border-b border-neutral-100 pb-2">
                         <Sprout className="w-4 h-4 text-emerald-600" />
                         <span>🔬 Soil Chemistry, N-P-K & Mineral Nutrition</span>
                       </div>
                      <p className="whitespace-pre-line leading-relaxed pb-3">{parseInlineStyles(report.soilNutrients)}</p>
                     </div>
     
                     <div className="grid grid-cols-1 md:grid-cols-2 gap-6 border-t border-neutral-50 pt-5">
                       {/* Watering */}
                       <div>
                        <div className="flex items-center gap-2 text-neutral-900 mb-3 pb-2 border-b border-neutral-100">
                           <Droplet className="w-4 h-4 text-blue-600" />
                          <h3 className="text-[10px] md:text-xs uppercase tracking-widest font-bold font-display">Watering Recommendations</h3>
                         </div>
                        <p className="text-sm md:text-[15px] text-neutral-800 leading-relaxed whitespace-pre-line">{parseInlineStyles(report.wateringAdvice)}</p>
                       </div>
     
                       {/* Sunlight */}
                       <div>
                        <div className="flex items-center gap-2 text-neutral-900 mb-3 pb-2 border-b border-neutral-100">
                           <Sun className="w-4 h-4 text-yellow-600 animate-spin-slow" style={{ animationDuration: "12s" }} />
                          <h3 className="text-[10px] md:text-xs uppercase tracking-widest font-bold font-display">Sunlight Exposure Guides</h3>
                         </div>
                        <p className="text-sm md:text-[15px] text-neutral-800 leading-relaxed whitespace-pre-line">{parseInlineStyles(report.sunlightAdvice)}</p>
                       </div>
                     </div>
                   </div>
                 </section>
    
                {/* 5. FOLLOW-UP ACTIONS CARD */}
                <section id="actions-sec" className="scroll-mt-6 animate-fade-in border-t border-neutral-100 pt-6">
                   <div className="space-y-5 animate-fade-in">
                     <div className="flex items-center gap-2 mb-3 border-b border-neutral-100 pb-2 justify-between">
                       <div className="flex items-center gap-2">
                         <HeartPulse className="w-4 h-4 text-rose-500 animate-pulse" />
                        <h2 className="text-xs md:text-sm font-bold text-neutral-500 uppercase tracking-widest font-display">
                           Chronological Recovery Action Plan (Nursing Checklist)
                         </h2>
                       </div>
                      <div className="text-[10px] md:text-xs text-neutral-500 font-semibold font-mono">
                         {Object.values(checkedRecoverySteps).filter(Boolean).length} / {report.recoverySteps.length} Finished
                       </div>
                     </div>
     
                    <p className="text-xs md:text-sm text-neutral-500 italic mb-4">
                       Interact with the checklist below to actively track your plant nursing progress step-by-step.
                     </p>
     
                     <div className="space-y-1">
                       {report.recoverySteps.map((step, idx) => {
                         const isCompleted = !!checkedRecoverySteps[idx];
                         return (
                           <div
                             key={idx}
                             onClick={() => toggleRecoveryStep(idx)}
                             className="py-2.5 cursor-pointer flex items-start gap-4 border-b border-neutral-50 last:border-b-0 hover:bg-neutral-50/50 px-1 rounded-md transition-colors"
                           >
                             <div
                              className={`w-5 h-5 rounded border flex items-center justify-center shrink-0 mt-0.5 transition-all ${
                                 isCompleted
                                   ? "bg-emerald-600 border-emerald-650 text-white"
                                   : "border-neutral-300 bg-white"
                               }`}
                             >
                              {isCompleted && <Check className="w-3.5 h-3.5 stroke-[3]" />}
                             </div>
                             <div className="min-w-0 flex-1">
                              <span className={`text-sm md:text-[15px] select-none block leading-relaxed ${isCompleted ? "line-through text-neutral-400" : "text-neutral-750 font-medium"}`}>
                                 {parseInlineStyles(step)}
                               </span>
                             </div>
                           </div>
                         );
                       })}
                     </div>
                   </div>
                 </section>
              </div>
            </>
          ) : (
            <div className="bg-emerald-50/40 border border-emerald-100 rounded-2xl p-6 sm:p-8 flex items-start gap-4 md:gap-5 animate-fade-in my-2">
              <div className="w-12 h-12 rounded-xl bg-emerald-105 flex items-center justify-center text-emerald-600 shrink-0 mt-0.5">
                <CheckCircle className="w-7 h-7 stroke-[2.5]" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-neutral-900 mb-1.5 font-display flex items-center gap-1.5">
                  Foliage Specimen is Healthy
                </h2>
                <p className="text-neutral-700 text-[15px] leading-relaxed">
                  Our botanical path analysis indicates this plant leaf is perfectly healthy! No active diseases, pathogens, insect bites, mineral deficiencies, or moisture decays were detected. You are doing a wonderful job maintaining this specimen!
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
